Repository ArkEcosystem/swift-client, pull requests merged in 2019-07, with the labels that each got.

#35 refactor: remove version argument remains
  Client/Client/Util.swift
Labels: Complexity: Low, Type: Refactor

#36 chore: remove redundant code
  Client/Cartfile
  Client/Cartfile.resolved
  Client/Client/Api/Endpoints/Node.swift
  Client/Client/Api/One/AccountsOne.swift
  Client/Client/Api/One/BlocksOne.swift
  Client/Client/Api/One/DelegatesOne.swift
  Client/Client/Api/One/LoaderOne.swift
  Client/Client/Api/One/One.swift
  Client/Client/Api/One/PeersOne.swift
  Client/Client/Api/One/SignaturesOne.swift
  Client/Client/Api/One/TransactionsOne.swift
Labels: Complexity: High, Type: Task

#37 chore: setup probot/stale configuration
  .github/stale.yml
Labels: Complexity: Low, Type: Task

#38 chore(readme): add lead maintainer information
  README.md
Labels: Complexity: Low, Type: Task
