Repository ArkEcosystem/swift-client, pull requests merged in 2019-05, with the labels that each got.

#29 chore: update contribution link
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Collaborator Approved, Type: Task

#31 feat: Add fees endpoint for Node class
  Client/Client/Api/Endpoints/Node.swift
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Feature

#32 chore: update sdk url
  README.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#33 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task
